name: CI

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions-contrib/go@v0.1.0
    - name: Build and test app
      run: make clean test
